---
- name: install apps
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - php
    - php-fpm
    - php-mbstring
    - php-dom  
  notify:
    - enable_n_autostart_nginx

- name: document root dir
  file:
    path: "{{ item.dir_path }}"
    state: directory
  loop:
    - {dir_path: "/opt/nginx/ansible"}
  notify:
    - reload_nginx    

- name: conveying files via template
  template:
    src: "{{item.src_file}}"
    dest: "{{item.dest_file}}"
  loop:
    - {
        src_file: "nginx.conf.j2",
        dest_file: "/etc/nginx/nginx.conf",
      }
    - {
      src_file: "fastcgi_params.j2",
      dest_file: "/etc/nginx/fastcgi_params",
    }
    - {
      src_file: "index.php.j2",
      dest_file: "/opt/nginx/ansible/index.php",
    }
  notify:
    - reload_nginx

- name: remove simlink default
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify:
    - reload_nginx
